
backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Inhalt", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Seiteneinstellungen"
    files:
      - label: "Allgemein"
        name: "site"
        file: "content/settings/site.json"
        fields:
          - {label: "Site-Titel", name: "title", widget: "string"}

